/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.manosbatsis.kotlinpoet.utils

import kotlin.test.Test
import kotlin.test.assertTrue

class BaseProcessorTest {
    @Test fun testSomeLibraryMethod() {
        //val classUnderTest = BaseProcessor()
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
